Repository masters2023-4th-project-carrot-talk/carrot-talk-be-a, pull requests merged in 2023-09, with the labels that each got.

#12 [be] 카테고리 API 구현
  be/carrot/src/main/java/com/example/carrot/category/controller/CategoryController.java
  be/carrot/src/main/java/com/example/carrot/category/dto/response/CategoryResponseDto.java
  be/carrot/src/main/java/com/example/carrot/category/repository/CategoryRepository.java
  be/carrot/src/main/java/com/example/carrot/category/service/CategoryService.java
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/location/entity/Location.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/user/repository/UserRepository.java
  be/carrot/src/main/java/com/example/carrot/user/service/UserService.java
Labels: back-end

#13 [be] 동네 조회 API 구현
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/location/controller/LocationController.java
  be/carrot/src/main/java/com/example/carrot/location/dto/response/LocationResponseDto.java
  be/carrot/src/main/java/com/example/carrot/location/entity/Location.java
  be/carrot/src/main/java/com/example/carrot/location/repository/LocationRepository.java
  be/carrot/src/main/java/com/example/carrot/location/service/LocationService.java
Labels: back-end

#31 [be] 대표 동네 등록 api 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/location/dto/request/MainLocationRequestDto.java
  be/carrot/src/main/java/com/example/carrot/location/dto/response/MainLocationResponseDto.java
  be/carrot/src/main/java/com/example/carrot/location/entity/Location.java
  be/carrot/src/main/java/com/example/carrot/user_location/controller/UserLocationController.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
  be/carrot/src/main/java/com/example/carrot/user_location/repository/UserLocationRepository.java
  be/carrot/src/main/java/com/example/carrot/user_location/service/UserLocationService.java
Labels: back-end

#30 [be] 동네 삭제 API 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/location/repository/LocationRepository.java
  be/carrot/src/main/java/com/example/carrot/user/controller/UserController.java
  be/carrot/src/main/java/com/example/carrot/user/dto/response/UserLocationDeleteResponseDto.java
  be/carrot/src/main/java/com/example/carrot/user/entity/User.java
  be/carrot/src/main/java/com/example/carrot/user/repository/UserRepository.java
  be/carrot/src/main/java/com/example/carrot/user/service/UserService.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
Labels: back-end

#34 [be] 수정 사항 반영
  be/carrot/src/main/java/com/example/carrot/global/common/ApiResponse.java
  be/carrot/src/main/java/com/example/carrot/global/config/WebConfig.java
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/user/controller/UserController.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
  be/carrot/src/main/java/com/example/carrot/user_location/service/UserLocationService.java
Labels: back-end

#35 [be] 충돌 해결 및 수정
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
  be/carrot/src/main/java/com/example/carrot/user_location/service/UserLocationService.java
Labels: back-end

#33 [be] 내 동네 조회 API 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/user_location/controller/UserLocationController.java
  be/carrot/src/main/java/com/example/carrot/user_location/dto/response/ReadUserLocationResponseDto.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
  be/carrot/src/main/java/com/example/carrot/user_location/service/UserLocationService.java
Labels: back-end

#38 [be] 전체 상품 조회 api 구현 완료
  be/carrot/build.gradle
  be/carrot/src/main/java/com/example/carrot/global/common/ApiResponse.java
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/MainPageResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductsResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/entity/ProductStatus.java
  be/carrot/src/main/java/com/example/carrot/product/repository/ProductRepository.java
  be/carrot/src/main/java/com/example/carrot/product/repository/ProductRepositoryCustom.java
  be/carrot/src/main/java/com/example/carrot/product/repository/ProductRepositoryCustomImpl.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
  be/carrot/src/main/java/com/example/carrot/user/controller/UserController.java
  be/carrot/src/main/java/com/example/carrot/user/entity/User.java
  be/carrot/src/main/java/com/example/carrot/user/repository/UserRepository.java
  be/carrot/src/main/java/com/example/carrot/user/service/UserService.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
  be/carrot/src/main/resources/data.sql
Labels: feat, back-end

#40 [be] 상품 수정 api 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/image/repository/ImageRepository.java
  be/carrot/src/main/java/com/example/carrot/location/repository/LocationRepository.java
  be/carrot/src/main/java/com/example/carrot/location/service/LocationService.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/ModifyProductRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ModifyProductResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
  be/carrot/src/main/java/com/example/carrot/product_image/entity/ProductImage.java
  be/carrot/src/main/java/com/example/carrot/product_image/repository/ProductImageRepository.java
  be/carrot/src/main/java/com/example/carrot/user/controller/UserController.java
  be/carrot/src/main/java/com/example/carrot/user/service/UserService.java
  be/carrot/src/main/java/com/example/carrot/user_location/controller/UserLocationController.java
  be/carrot/src/main/java/com/example/carrot/user_location/service/UserLocationService.java
  be/carrot/src/main/resources/data.sql
Labels: feat, back-end

#44 [be] 3주차 피드백 반영
  be/carrot/src/main/java/com/example/carrot/category/entity/Category.java
  be/carrot/src/main/java/com/example/carrot/global/exception/GlobalExceptionHandler.java
  be/carrot/src/main/java/com/example/carrot/image/entity/Image.java
  be/carrot/src/main/java/com/example/carrot/like/entity/Like.java
  be/carrot/src/main/java/com/example/carrot/location/entity/Location.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product_image/entity/ProductImage.java
  be/carrot/src/main/java/com/example/carrot/user/entity/User.java
  be/carrot/src/main/java/com/example/carrot/user_location/entity/UserLocation.java
Labels: back-end

#45 [be] 상품 등록 api 구현
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/SaveProductRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/SaveProductResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: back-end

#47 [be] 상품 삭제 api 구현
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
  be/carrot/src/main/java/com/example/carrot/user/service/UserService.java
Labels: feat, back-end

#48 feat #29: 상품 상태 수정 API 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/ModifyProductStatusRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ModifyProductResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/entity/ProductStatus.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: feat, back-end

#49 [be] 상품 좋아요 수정 API 구현
  be/carrot/src/main/java/com/example/carrot/like/controller/LikeController.java
  be/carrot/src/main/java/com/example/carrot/like/dto/response/ModifyLikeResponseDto.java
  be/carrot/src/main/java/com/example/carrot/like/repository/LikeRepository.java
  be/carrot/src/main/java/com/example/carrot/like/service/LikeService.java
Labels: feat, back-end

#46 [be] 상품 상세 조회 API 구현
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductDetailResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductDetailSellerResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductsResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ReadProductDetailResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/entity/ProductStatus.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: bug, back-end

#50 [be] 상품 등록 API 이미지 관련 리팩토링
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: back-end

#51 [be] 3주차 피드백 및 수정 사항 반영
  be/carrot/src/main/java/com/example/carrot/global/config/AuthConfig.java
  be/carrot/src/main/java/com/example/carrot/global/exception/ErrorCode.java
  be/carrot/src/main/java/com/example/carrot/global/exception/ExceptionToStatusCodeMapper.java
  be/carrot/src/main/java/com/example/carrot/global/exception/GlobalExceptionHandler.java
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/ModifyProductRequestDto.java
Labels: back-end

#52 [be] 3주차 피드백 반영
  be/carrot/src/main/java/com/example/carrot/global/filter/AuthFilter.java
  be/carrot/src/main/java/com/example/carrot/product/repository/ProductRepository.java
  be/carrot/src/main/java/com/example/carrot/product/repository/QueryProductRepository.java
  be/carrot/src/main/java/com/example/carrot/product/repository/QueryProductRepositoryImpl.java
Labels: back-end

#53 [be] 이미지 업로드 API 구현
  be/carrot/build.gradle
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/image/component/ImageS3Uploader.java
  be/carrot/src/main/java/com/example/carrot/image/controller/ImageController.java
  be/carrot/src/main/java/com/example/carrot/image/dto/ImageFormat.java
  be/carrot/src/main/java/com/example/carrot/image/dto/response/ImageResponse.java
  be/carrot/src/main/java/com/example/carrot/image/entity/Image.java
  be/carrot/src/main/java/com/example/carrot/image/service/ImageService.java
Labels: back-end

#55 [be] 버그 fix
  be/carrot/src/main/java/com/example/carrot/category/controller/CategoryController.java
  be/carrot/src/main/java/com/example/carrot/category/dto/response/CategoryResponseDto.java
  be/carrot/src/main/java/com/example/carrot/category/service/CategoryService.java
  be/carrot/src/main/java/com/example/carrot/image/component/ImageS3Uploader.java
  be/carrot/src/main/java/com/example/carrot/image/entity/ImageFormat.java
  be/carrot/src/main/java/com/example/carrot/location/entity/Location.java
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/SaveProductRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: back-end

#68 fix #43: 상품 수정 api 리팩토링
  be/carrot/src/main/java/com/example/carrot/product/controller/ProductController.java
  be/carrot/src/main/java/com/example/carrot/product/dto/request/ModifyProductRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/entity/ProductDetails.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
  be/carrot/src/main/java/com/example/carrot/product_image/repository/ProductImageRepository.java
Labels: back-end

#94 [be] fix #92: Location Response 수정
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductDetailLocationResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductDetailResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ReadProductDetailResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: back-end

#104 fix #103: product 관련 api name -> title 변경
  be/carrot/src/main/java/com/example/carrot/product/dto/request/SaveProductRequestDto.java
  be/carrot/src/main/java/com/example/carrot/product/dto/response/ProductsResponseDto.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/product/repository/QueryProductRepositoryImpl.java
  be/carrot/src/main/java/com/example/carrot/product/service/ProductService.java
Labels: back-end

#108 [BE] 채팅방 만들기 API 구현
  be/carrot/build.gradle
  be/carrot/src/main/java/com/example/carrot/chat_message/entity/ChatMessage.java
  be/carrot/src/main/java/com/example/carrot/chat_room/controller/ChatRoomController.java
  be/carrot/src/main/java/com/example/carrot/chat_room/dto/request/ChatRoomRequestDto.java
  be/carrot/src/main/java/com/example/carrot/chat_room/dto/response/ChatRoomResponseDto.java
  be/carrot/src/main/java/com/example/carrot/chat_room/entity/ChatRoom.java
  be/carrot/src/main/java/com/example/carrot/chat_room/repository/ChatRoomRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_room/service/ChatRoomService.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/user/entity/User.java
Labels: back-end

#115 [be] 채팅 보내기 구현
  be/carrot/build.gradle
  be/carrot/src/main/java/com/example/carrot/chat_message/controller/ChatMessageController.java
  be/carrot/src/main/java/com/example/carrot/chat_message/dto/Entry.java
  be/carrot/src/main/java/com/example/carrot/chat_message/dto/MessageDto.java
  be/carrot/src/main/java/com/example/carrot/chat_message/entity/ChatMessage.java
  be/carrot/src/main/java/com/example/carrot/chat_message/repository/ChatMessageRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/ChatMessageService.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/MessageReceivedEvent.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/MessageReceivedEventListener.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/message/MessagePublisher.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/message/MessageSubscriber.java
  be/carrot/src/main/java/com/example/carrot/chat_room/entity/ChatRoom.java
  be/carrot/src/main/java/com/example/carrot/chat_room/entity/ChatRoomSession.java
  be/carrot/src/main/java/com/example/carrot/chat_room/repository/ChatRoomSessionRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_room/service/ChatRoomService.java
  be/carrot/src/main/java/com/example/carrot/global/config/RedisConfig.java
  be/carrot/src/main/java/com/example/carrot/global/config/WebSocketConfig.java
  be/carrot/src/main/java/com/example/carrot/global/exception/StatusCode.java
  be/carrot/src/main/java/com/example/carrot/global/interceptor/StompHandler.java
  be/carrot/src/main/java/com/example/carrot/notification/component/FCMInitializer.java
  be/carrot/src/main/java/com/example/carrot/notification/dao/FCMTokenDao.java
  be/carrot/src/main/java/com/example/carrot/notification/service/FCMService.java
  be/carrot/src/main/java/com/example/carrot/user/controller/UserController.java
Labels: feat, back-end

#119 [BE] feat #118: 안 읽은 전체 채팅 개수 조회 API 구현
  be/carrot/src/main/java/com/example/carrot/chat_room/controller/ChatRoomController.java
  be/carrot/src/main/java/com/example/carrot/chat_room/dto/response/UnReadCountResponseDto.java
  be/carrot/src/main/java/com/example/carrot/chat_room/repository/ChatRoomRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_room/service/ChatRoomService.java
  be/carrot/src/main/java/com/example/carrot/product/entity/Product.java
  be/carrot/src/main/java/com/example/carrot/user/entity/User.java
Labels: feat, back-end

#129 [be] 채팅 내역 조회 API 구현
  be/carrot/src/main/java/com/example/carrot/chat_message/controller/ChatMessageController.java
  be/carrot/src/main/java/com/example/carrot/chat_message/repository/ChatMessageRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_message/repository/QueryChatMessageRepository.java
  be/carrot/src/main/java/com/example/carrot/chat_message/repository/QueryChatMessageRepositoryImpl.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/MessageReceivedEventListener.java
  be/carrot/src/main/java/com/example/carrot/chat_message/service/message/MessageSubscriber.java
  be/carrot/src/main/java/com/example/carrot/chat_room/controller/ChatRoomController.java
  be/carrot/src/main/java/com/example/carrot/chat_room/dto/response/ChatMessageResponseDto.java
  be/carrot/src/main/java/com/example/carrot/chat_room/dto/response/ChatMessageResponseDtos.java
  be/carrot/src/main/java/com/example/carrot/chat_room/entity/ChatRoomSession.java
  be/carrot/src/main/java/com/example/carrot/chat_room/service/ChatRoomService.java
  be/carrot/src/main/java/com/example/carrot/global/config/RedisConfig.java
Labels: feat, back-end
